Nizam Shaikh - 24198170

**Read Bank Statment File**

In [1]:
import pandas as pd
df = pd.read_csv("bankstatements.csv")

In [2]:
df.head()

         date DrCr   amount    balance mode      name  Day  Month  Year  Tday
0  01/01/2022   Db  10000.0  473292.87  ATM       NaN    1      1  2022     1
1  01/01/2022   Db  10000.0  463292.87  ATM       NaN    1      1  2022     1
2  02/01/2022   Db    930.0  462362.87  UPI  AYUBRAJE    2      1  2022     2
3  07/01/2022   Db   2000.0  460362.87  UPI  ABUTALAH    7      1  2022     3
4  10/01/2022   Db   1000.0  459362.87  UPI  AGRAWALB   10      1  2022     4

**Task 1: Selecting Specific Columns**

Select the 'date' and 'amount' columns

In [3]:
# Select the 'date' and 'amount' columns
SC = df[["date", "amount"]]
SC

           date   amount
0    01/01/2022  10000.0
1    01/01/2022  10000.0
2    02/01/2022    930.0
3    07/01/2022   2000.0
4    10/01/2022   1000.0
..          ...      ...
504  06/10/2023  41050.0
505  06/10/2023    107.8
506  06/10/2023  23586.0
507  06/10/2023  26286.0
508  07/10/2023    100.0

[509 rows x 2 columns]

**Task 2: Selecting Rows Based on a Condition**

Select transactions where the amount is greater than 1000

In [4]:
# Select transactions where the amount is greater than 1000
SR = df[df["amount"] > 1000]
SR

,date,DrCr,amount,balance,mode,name,Day,Month,Year,Tday
0,01/01/2022,Db,10000.0,473292.87,ATM,NaN,1,1,2022,1
1,01/01/2022,Db,10000.0,463292.87,ATM,NaN,1,1,2022,1
3,07/01/2022,Db,2000.0,460362.87,UPI,ABUTALAH,7,1,2022,3
5,10/01/2022,Db,1800.0,457562.87,UPI,GOASELEC,10,1,2022,4
6,10/01/2022,Db,5000.0,452562.87,UPI,GOASELEC,10,1,2022,4
...,...,...,...,...,...,...,...,...,...,...
499,04/10/2023,Db,26286.0,5246.67,UPI,DADAKHALA,4,10,2023,310
502,05/10/2023,Cr,51905.0,56645.67,NEFT,NaN,5,10,2023,311
504,06/10/2023,Cr,41050.0,97647.67,CHEQUE,NaN,6,10,2023,312
506,06/10/2023,Cr,23586.0,121341.47,UPI,DADAKHALA,6,10,2023,312
507,06/10/2023,Db,26286.0,95055.47,UPI,HDFCBANK,6,10,2023,312

**Task 3: Selecting Rows Based on Multiple Conditions**

Select transactions in January 2022 with amount > 5000

In [5]:
# Select transactions in January 2022 with amount > 5000
SRM = df[(df["Month"] == 1) & (df["Year"] == 2022) & (df["amount"] > 5000)]
SRM

,date,DrCr,amount,balance,mode,name,Day,Month,Year,Tday
0,01/01/2022,Db,10000.0,473292.87,ATM,NaN,1,1,2022,1
1,01/01/2022,Db,10000.0,463292.87,ATM,NaN,1,1,2022,1
15,14/01/2022,Db,7000.0,444040.87,UPI,BUDESAHEB,14,1,2022,7

**Task 4:Sort transactions by date in ascending order**

In [6]:
# Sort transactions by date in ascending order
SD = df.sort_values(by=["date"], ascending=True)
SD

,date,DrCr,amount,balance,mode,name,Day,Month,Year,Tday
0,01/01/2022,Db,10000.0,473292.87,ATM,NaN,1,1,2022,1
1,01/01/2022,Db,10000.0,463292.87,ATM,NaN,1,1,2022,1
261,01/01/2023,Db,6005.0,98980.04,UPI,MEHTAMOH,1,1,2023,169
260,01/01/2023,Cr,5.0,104985.04,UPI,MEHTAMOH,1,1,2023,169
20,01/02/2022,Cr,3187.0,449303.96,SBINT,NaN,1,2,2022,11
...,...,...,...,...,...,...,...,...,...,...
291,31/01/2023,Db,5000.0,34885.13,ATM,NaN,31,1,2023,184
64,31/03/2022,Db,4000.0,230283.96,UPI,ABUTALAH,31,3,2022,38
432,31/07/2023,Db,3020.0,11491.33,UPI,SUNILKA,31,7,2023,273
206,31/10/2022,Db,2000.0,14967.75,UPI,ABUTALAH,31,10,2022,137
259,31/12/2022,Cr,41699.0,104980.04,NEFT,NaN,31,12,2022,168

**Task 5: Calculate the total amount of all transactions**

In [7]:
# Calculate the total amount of all transactions
TA = df["amount"].sum()
TA

np.float64(4446854.58)

**Task 6: Grouping Data**

In [8]:
# Group transactions by mode and calculate the average amount for each mode
GD = df.groupby("mode")["amount"].mean()
GD

mode
ATM                       7919.571429
CHEQUE                  180210.000000
DEBIT CARD ANNUAL          145.000000
ECS                         45.477727
FUNDS TRANSFER DEBIT    198615.000000
IMPS                      4375.750000
NEFT                     31882.815135
OTHER                       20.000000
SBINT                     1152.000000
SMS CHARGES                 15.142857
STOCK CHRG                  59.000000
UNKNOWN                  33571.000000
UPI                       4108.591649
Name: amount, dtype: float64

**Task 7: Creating New Columns**

In [9]:
# Create a new column 'transaction_type' based on 'DrCr'
df["transaction_type"] = df["DrCr"].map({"Db": "Debit", "Cr": "Credit"})
df.head()

,date,DrCr,amount,balance,mode,name,Day,Month,Year,Tday,transaction_type
0,01/01/2022,Db,10000.0,473292.87,ATM,NaN,1,1,2022,1,Debit
1,01/01/2022,Db,10000.0,463292.87,ATM,NaN,1,1,2022,1,Debit
2,02/01/2022,Db,930.0,462362.87,UPI,AYUBRAJE,2,1,2022,2,Debit
3,07/01/2022,Db,2000.0,460362.87,UPI,ABUTALAH,7,1,2022,3,Debit
4,10/01/2022,Db,1000.0,459362.87,UPI,AGRAWALB,10,1,2022,4,Debit

**Task 8: Renaming Columns**

In [10]:
# Rename the 'amount' column to 'transaction_amount'
df = df.rename(columns={"Tday": "Transaction_Day"})
df.head()

,date,DrCr,amount,balance,mode,name,Day,Month,Year,Transaction_Day,transaction_type
0,01/01/2022,Db,10000.0,473292.87,ATM,NaN,1,1,2022,1,Debit
1,01/01/2022,Db,10000.0,463292.87,ATM,NaN,1,1,2022,1,Debit
2,02/01/2022,Db,930.0,462362.87,UPI,AYUBRAJE,2,1,2022,2,Debit
3,07/01/2022,Db,2000.0,460362.87,UPI,ABUTALAH,7,1,2022,3,Debit
4,10/01/2022,Db,1000.0,459362.87,UPI,AGRAWALB,10,1,2022,4,Debit

**Task 9: Dropping Columns**

In [11]:
# Drop the 'Tday' column
df = df.drop(columns=["transaction_type"])
df

,date,DrCr,amount,balance,mode,name,Day,Month,Year,Transaction_Day
0,01/01/2022,Db,10000.0,473292.87,ATM,NaN,1,1,2022,1
1,01/01/2022,Db,10000.0,463292.87,ATM,NaN,1,1,2022,1
2,02/01/2022,Db,930.0,462362.87,UPI,AYUBRAJE,2,1,2022,2
3,07/01/2022,Db,2000.0,460362.87,UPI,ABUTALAH,7,1,2022,3
4,10/01/2022,Db,1000.0,459362.87,UPI,AGRAWALB,10,1,2022,4
...,...,...,...,...,...,...,...,...,...,...
504,06/10/2023,Cr,41050.0,97647.67,CHEQUE,NaN,6,10,2023,312
505,06/10/2023,Cr,107.8,97755.47,ECS,NaN,6,10,2023,312
506,06/10/2023,Cr,23586.0,121341.47,UPI,DADAKHALA,6,10,2023,312
507,06/10/2023,Db,26286.0,95055.47,UPI,HDFCBANK,6,10,2023,312
508,07/10/2023,Db,100.0,94955.47,UPI,LAGADEKSA,7,10,2023,313

**Task 10: Handling Missing Values**

In [18]:
# Fill missing values in the 'name' column with 'Unknown'
df["name"] = df["name"].fillna("Nizam")
df

,date,DrCr,amount,balance,mode,name,Day,Month,Year,Transaction_Day
0,01/01/2022,Db,10000.0,473292.87,ATM,Nizam,1,1,2022,1
1,01/01/2022,Db,10000.0,463292.87,ATM,Nizam,1,1,2022,1
2,02/01/2022,Db,930.0,462362.87,UPI,AYUBRAJE,2,1,2022,2
3,07/01/2022,Db,2000.0,460362.87,UPI,ABUTALAH,7,1,2022,3
4,10/01/2022,Db,1000.0,459362.87,UPI,AGRAWALB,10,1,2022,4
...,...,...,...,...,...,...,...,...,...,...
504,06/10/2023,Cr,41050.0,97647.67,CHEQUE,Nizam,6,10,2023,312
505,06/10/2023,Cr,107.8,97755.47,ECS,Nizam,6,10,2023,312
506,06/10/2023,Cr,23586.0,121341.47,UPI,DADAKHALA,6,10,2023,312
507,06/10/2023,Db,26286.0,95055.47,UPI,HDFCBANK,6,10,2023,312
508,07/10/2023,Db,100.0,94955.47,UPI,LAGADEKSA,7,10,2023,313

**Task 11: Filtering Based on String Contains**

In [20]:
# Select transactions where the name contains 'AYUB'
FS = df[df["name"].str.contains("Nizam")]
FS

,date,DrCr,amount,balance,mode,name,Day,Month,Year,Transaction_Day
0,01/01/2022,Db,10000.00,473292.87,ATM,Nizam,1,1,2022,1
1,01/01/2022,Db,10000.00,463292.87,ATM,Nizam,1,1,2022,1
8,10/01/2022,Cr,2400.00,451962.87,NEFT,Nizam,10,1,2022,4
17,25/01/2022,Cr,7.09,443858.96,ECS,Nizam,25,1,2022,9
18,29/01/2022,Cr,2400.00,446258.96,NEFT,Nizam,29,1,2022,10
...,...,...,...,...,...,...,...,...,...,...
489,23/09/2023,Db,17.00,51691.67,SMS CHARGES,Nizam,23,9,2023,305
495,27/09/2023,Db,10000.00,36662.67,ATM,Nizam,27,9,2023,307
502,05/10/2023,Cr,51905.00,56645.67,NEFT,Nizam,5,10,2023,311
504,06/10/2023,Cr,41050.00,97647.67,CHEQUE,Nizam,6,10,2023,312
505,06/10/2023,Cr,107.80,97755.47,ECS,Nizam,6,10,2023,312

**Task 12: Extracting Date Components**

In [33]:
# Extract the day of the week from the 'date' column
df["date"] = pd.to_datetime(df["date"], dayfirst=True)
df["week_name_days"] = df["date"].dt.day_name()
df

,date,DrCr,amount,balance,mode,name,Day,Month,Year,Transaction_Day,week_name_days
0,2022-01-01,Db,10000.0,473292.87,ATM,Nizam,1,1,2022,1,Saturday
1,2022-01-01,Db,10000.0,463292.87,ATM,Nizam,1,1,2022,1,Saturday
2,2022-01-02,Db,930.0,462362.87,UPI,AYUBRAJE,2,1,2022,2,Sunday
3,2022-01-07,Db,2000.0,460362.87,UPI,ABUTALAH,7,1,2022,3,Friday
4,2022-01-10,Db,1000.0,459362.87,UPI,AGRAWALB,10,1,2022,4,Monday
...,...,...,...,...,...,...,...,...,...,...,...
504,2023-10-06,Cr,41050.0,97647.67,CHEQUE,Nizam,6,10,2023,312,Friday
505,2023-10-06,Cr,107.8,97755.47,ECS,Nizam,6,10,2023,312,Friday
506,2023-10-06,Cr,23586.0,121341.47,UPI,DADAKHALA,6,10,2023,312,Friday
507,2023-10-06,Db,26286.0,95055.47,UPI,HDFCBANK,6,10,2023,312,Friday
508,2023-10-07,Db,100.0,94955.47,UPI,LAGADEKSA,7,10,2023,313,Saturday

**Task 13: Applying a Function to a Column**

In [35]:
# Apply a function to double the 'amount' column
df["Multiply_amount"] = df["amount"].apply(lambda x: x * 2)
df

,date,DrCr,amount,balance,mode,name,Day,Month,Year,Transaction_Day,week_name_days,Multiply_amount
0,2022-01-01,Db,10000.0,473292.87,ATM,Nizam,1,1,2022,1,Saturday,20000.0
1,2022-01-01,Db,10000.0,463292.87,ATM,Nizam,1,1,2022,1,Saturday,20000.0
2,2022-01-02,Db,930.0,462362.87,UPI,AYUBRAJE,2,1,2022,2,Sunday,1860.0
3,2022-01-07,Db,2000.0,460362.87,UPI,ABUTALAH,7,1,2022,3,Friday,4000.0
4,2022-01-10,Db,1000.0,459362.87,UPI,AGRAWALB,10,1,2022,4,Monday,2000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
504,2023-10-06,Cr,41050.0,97647.67,CHEQUE,Nizam,6,10,2023,312,Friday,82100.0
505,2023-10-06,Cr,107.8,97755.47,ECS,Nizam,6,10,2023,312,Friday,215.6
506,2023-10-06,Cr,23586.0,121341.47,UPI,DADAKHALA,6,10,2023,312,Friday,47172.0
507,2023-10-06,Db,26286.0,95055.47,UPI,HDFCBANK,6,10,2023,312,Friday,52572.0
508,2023-10-07,Db,100.0,94955.47,UPI,LAGADEKSA,7,10,2023,313,Saturday,200.0

**Task 14: Counting Unique Values**

In [36]:
# Count the number of unique transaction modes
unique_values = df['mode'].nunique()
unique_values

13

**Task 15: Checking for Duplicates**

In [37]:
# Find and display duplicate rows
duplicates = df[df.duplicated()]
duplicates

,date,DrCr,amount,balance,mode,name,Day,Month,Year,Transaction_Day,week_name_days,Multiply_amount
307,2023-02-16,Db,5000.0,30744.13,ATM,Nizam,16,2,2023,194,Thursday,10000.0