In [19]:
import pandas as pd

# Read the CSV file into a pandas DataFrame
df = pd.read_csv('/content/bankstatements.csv')

# Display the first few rows of the DataFrame
df.head()

         date DrCr   amount    balance mode      name  Day  Month  Year  Tday
0  2022-01-01   Db  10000.0  473292.87  ATM       NaN    1      1  2022     1
1  2022-01-01   Db  10000.0  463292.87  ATM       NaN    1      1  2022     1
2  2022-01-02   Db    930.0  462362.87  UPI  AYUBRAJE    2      1  2022     2
3  2022-01-07   Db   2000.0  460362.87  UPI  ABUTALAH    7      1  2022     3
4  2022-01-10   Db   1000.0  459362.87  UPI  AGRAWALB   10      1  2022     4

**Task 1: Selecting Specific Columns**

Select the 'date' and 'amount' columns

In [20]:
# Select the 'date' and 'amount' columns
selected_columns = df[['date', 'amount']]
selected_columns

           date   amount
0    2022-01-01  10000.0
1    2022-01-01  10000.0
2    2022-01-02    930.0
3    2022-01-07   2000.0
4    2022-01-10   1000.0
..          ...      ...
504  2023-10-06  41050.0
505  2023-10-06    107.8
506  2023-10-06  23586.0
507  2023-10-06  26286.0
508  2023-10-07    100.0

[509 rows x 2 columns]

**Task 2: Selecting Rows Based on a Condition**

Select transactions where the amount is greater than 1000

In [21]:
# Select transactions where the amount is greater than 1000
filtered_rows = df[df['amount'] > 1000]
filtered_rows

,date,DrCr,amount,balance,mode,name,Day,Month,Year,Tday
0,2022-01-01,Db,10000.0,473292.87,ATM,NaN,1,1,2022,1
1,2022-01-01,Db,10000.0,463292.87,ATM,NaN,1,1,2022,1
3,2022-01-07,Db,2000.0,460362.87,UPI,ABUTALAH,7,1,2022,3
5,2022-01-10,Db,1800.0,457562.87,UPI,GOASELEC,10,1,2022,4
6,2022-01-10,Db,5000.0,452562.87,UPI,GOASELEC,10,1,2022,4
...,...,...,...,...,...,...,...,...,...,...
499,2023-10-04,Db,26286.0,5246.67,UPI,DADAKHALA,4,10,2023,310
502,2023-10-05,Cr,51905.0,56645.67,NEFT,NaN,5,10,2023,311
504,2023-10-06,Cr,41050.0,97647.67,CHEQUE,NaN,6,10,2023,312
506,2023-10-06,Cr,23586.0,121341.47,UPI,DADAKHALA,6,10,2023,312
507,2023-10-06,Db,26286.0,95055.47,UPI,HDFCBANK,6,10,2023,312

**Task 3: Selecting Rows Based on Multiple Conditions**

Select transactions in January 2022 with amount > 5000

In [22]:
# Select transactions in January 2022 with amount > 5000
filtered_rows = df[(df['Month'] == 1) & (df['Year'] == 2022) & (df['amount'] > 5000)]
filtered_rows

,date,DrCr,amount,balance,mode,name,Day,Month,Year,Tday
0,2022-01-01,Db,10000.0,473292.87,ATM,NaN,1,1,2022,1
1,2022-01-01,Db,10000.0,463292.87,ATM,NaN,1,1,2022,1
15,2022-01-14,Db,7000.0,444040.87,UPI,BUDESAHEB,14,1,2022,7

**Task 4:Sort transactions by date in ascending order**

In [23]:
# Sort transactions by date in ascending order
sorted_data = df.sort_values(by=['date'])
sorted_data

,date,DrCr,amount,balance,mode,name,Day,Month,Year,Tday
0,2022-01-01,Db,10000.0,473292.87,ATM,NaN,1,1,2022,1
1,2022-01-01,Db,10000.0,463292.87,ATM,NaN,1,1,2022,1
2,2022-01-02,Db,930.0,462362.87,UPI,AYUBRAJE,2,1,2022,2
3,2022-01-07,Db,2000.0,460362.87,UPI,ABUTALAH,7,1,2022,3
4,2022-01-10,Db,1000.0,459362.87,UPI,AGRAWALB,10,1,2022,4
...,...,...,...,...,...,...,...,...,...,...
506,2023-10-06,Cr,23586.0,121341.47,UPI,DADAKHALA,6,10,2023,312
507,2023-10-06,Db,26286.0,95055.47,UPI,HDFCBANK,6,10,2023,312
504,2023-10-06,Cr,41050.0,97647.67,CHEQUE,NaN,6,10,2023,312
505,2023-10-06,Cr,107.8,97755.47,ECS,NaN,6,10,2023,312
508,2023-10-07,Db,100.0,94955.47,UPI,LAGADEKSA,7,10,2023,313

**Task 5: Calculate the total amount of all transactions**

In [24]:
# Calculate the total amount of all transactions
total_amount = df['amount'].sum()
total_amount

4446854.58

**Task 6: Grouping Data**

In [25]:
# Group transactions by mode and calculate the average amount for each mode
grouped_data = df.groupby('mode')['amount'].mean()
grouped_data

mode
ATM                       7919.571429
CHEQUE                  180210.000000
DEBIT CARD ANNUAL          145.000000
ECS                         45.477727
FUNDS TRANSFER DEBIT    198615.000000
IMPS                      4375.750000
NEFT                     31882.815135
OTHER                       20.000000
SBINT                     1152.000000
SMS CHARGES                 15.142857
STOCK CHRG                  59.000000
UNKNOWN                  33571.000000
UPI                       4108.591649
Name: amount, dtype: float64

**Task 7: Creating New Columns**

In [26]:
# Create a new column 'transaction_type' based on 'DrCr'
df['transaction_type'] = df['DrCr'].map({'Db': 'Debit', 'Cr': 'Credit'})
df

,date,DrCr,amount,balance,mode,name,Day,Month,Year,Tday,transaction_type
0,2022-01-01,Db,10000.0,473292.87,ATM,NaN,1,1,2022,1,Debit
1,2022-01-01,Db,10000.0,463292.87,ATM,NaN,1,1,2022,1,Debit
2,2022-01-02,Db,930.0,462362.87,UPI,AYUBRAJE,2,1,2022,2,Debit
3,2022-01-07,Db,2000.0,460362.87,UPI,ABUTALAH,7,1,2022,3,Debit
4,2022-01-10,Db,1000.0,459362.87,UPI,AGRAWALB,10,1,2022,4,Debit
...,...,...,...,...,...,...,...,...,...,...,...
504,2023-10-06,Cr,41050.0,97647.67,CHEQUE,NaN,6,10,2023,312,Credit
505,2023-10-06,Cr,107.8,97755.47,ECS,NaN,6,10,2023,312,Credit
506,2023-10-06,Cr,23586.0,121341.47,UPI,DADAKHALA,6,10,2023,312,Credit
507,2023-10-06,Db,26286.0,95055.47,UPI,HDFCBANK,6,10,2023,312,Debit
508,2023-10-07,Db,100.0,94955.47,UPI,LAGADEKSA,7,10,2023,313,Debit

**Task 8: Renaming Columns**

In [27]:
# Rename the 'amount' column to 'transaction_amount'
df = df.rename(columns={'amount': 'transaction_amount'})
df

,date,DrCr,transaction_amount,balance,mode,name,Day,Month,Year,Tday,transaction_type
0,2022-01-01,Db,10000.0,473292.87,ATM,NaN,1,1,2022,1,Debit
1,2022-01-01,Db,10000.0,463292.87,ATM,NaN,1,1,2022,1,Debit
2,2022-01-02,Db,930.0,462362.87,UPI,AYUBRAJE,2,1,2022,2,Debit
3,2022-01-07,Db,2000.0,460362.87,UPI,ABUTALAH,7,1,2022,3,Debit
4,2022-01-10,Db,1000.0,459362.87,UPI,AGRAWALB,10,1,2022,4,Debit
...,...,...,...,...,...,...,...,...,...,...,...
504,2023-10-06,Cr,41050.0,97647.67,CHEQUE,NaN,6,10,2023,312,Credit
505,2023-10-06,Cr,107.8,97755.47,ECS,NaN,6,10,2023,312,Credit
506,2023-10-06,Cr,23586.0,121341.47,UPI,DADAKHALA,6,10,2023,312,Credit
507,2023-10-06,Db,26286.0,95055.47,UPI,HDFCBANK,6,10,2023,312,Debit
508,2023-10-07,Db,100.0,94955.47,UPI,LAGADEKSA,7,10,2023,313,Debit

**Task 9: Dropping Columns**

In [28]:
# Drop the 'Tday' column
df = df.drop(columns=['Tday'])
df

,date,DrCr,transaction_amount,balance,mode,name,Day,Month,Year,transaction_type
0,2022-01-01,Db,10000.0,473292.87,ATM,NaN,1,1,2022,Debit
1,2022-01-01,Db,10000.0,463292.87,ATM,NaN,1,1,2022,Debit
2,2022-01-02,Db,930.0,462362.87,UPI,AYUBRAJE,2,1,2022,Debit
3,2022-01-07,Db,2000.0,460362.87,UPI,ABUTALAH,7,1,2022,Debit
4,2022-01-10,Db,1000.0,459362.87,UPI,AGRAWALB,10,1,2022,Debit
...,...,...,...,...,...,...,...,...,...,...
504,2023-10-06,Cr,41050.0,97647.67,CHEQUE,NaN,6,10,2023,Credit
505,2023-10-06,Cr,107.8,97755.47,ECS,NaN,6,10,2023,Credit
506,2023-10-06,Cr,23586.0,121341.47,UPI,DADAKHALA,6,10,2023,Credit
507,2023-10-06,Db,26286.0,95055.47,UPI,HDFCBANK,6,10,2023,Debit
508,2023-10-07,Db,100.0,94955.47,UPI,LAGADEKSA,7,10,2023,Debit

**Task 10: Handling Missing Values**

In [29]:
# Fill missing values in the 'name' column with 'Unknown'
df['name'] = df['name'].fillna('Unknown')
df

,date,DrCr,transaction_amount,balance,mode,name,Day,Month,Year,transaction_type
0,2022-01-01,Db,10000.0,473292.87,ATM,Unknown,1,1,2022,Debit
1,2022-01-01,Db,10000.0,463292.87,ATM,Unknown,1,1,2022,Debit
2,2022-01-02,Db,930.0,462362.87,UPI,AYUBRAJE,2,1,2022,Debit
3,2022-01-07,Db,2000.0,460362.87,UPI,ABUTALAH,7,1,2022,Debit
4,2022-01-10,Db,1000.0,459362.87,UPI,AGRAWALB,10,1,2022,Debit
...,...,...,...,...,...,...,...,...,...,...
504,2023-10-06,Cr,41050.0,97647.67,CHEQUE,Unknown,6,10,2023,Credit
505,2023-10-06,Cr,107.8,97755.47,ECS,Unknown,6,10,2023,Credit
506,2023-10-06,Cr,23586.0,121341.47,UPI,DADAKHALA,6,10,2023,Credit
507,2023-10-06,Db,26286.0,95055.47,UPI,HDFCBANK,6,10,2023,Debit
508,2023-10-07,Db,100.0,94955.47,UPI,LAGADEKSA,7,10,2023,Debit

**Task 11: Filtering Based on String Contains**

In [30]:
# Select transactions where the name contains 'AYUB'
filtered_rows = df[df['name'].str.contains('AYUB', na=False)]
filtered_rows

,date,DrCr,transaction_amount,balance,mode,name,Day,Month,Year,transaction_type
2,2022-01-02,Db,930.0,462362.87,UPI,AYUBRAJE,2,1,2022,Debit
21,2022-02-02,Db,750.0,448553.96,UPI,AYUBRAJE,2,2,2022,Debit
42,2022-03-01,Db,800.0,414909.96,UPI,AYUBRAJE,1,3,2022,Debit
65,2022-04-02,Db,992.0,229291.96,UPI,AYUBRAJE,2,4,2022,Debit
82,2022-05-02,Db,928.0,100829.96,UPI,AYUBRAJE,2,5,2022,Debit
103,2022-06-03,Db,832.0,175317.05,UPI,AYUBRAJE,3,6,2022,Debit
124,2022-07-04,Db,960.0,138107.14,UPI,AYUBRAJE,4,7,2022,Debit
145,2022-08-03,Db,1120.0,74837.14,UPI,AYUBRAJE,3,8,2022,Debit
170,2022-09-03,Db,980.0,417671.23,UPI,AYUBRAJE,3,9,2022,Debit
191,2022-10-01,Db,980.0,92429.73,UPI,AYUBRAJE,1,10,2022,Debit
212,2022-11-04,Db,805.0,62034.75,UPI,AYUBRAJE,4,11,2022,Debit
235,2022-12-03,Db,420.0,95432.75,UPI,AYUBRAJE,3,12,2022,Debit
503,2023-10-05,Db,48.0,56597.67,UPI,AYUBRAJE,5,10,2023,Debit

**Task 12: Extracting Date Components**

In [31]:
# Extract the day of the week from the 'date' column
df['day_of_week'] = pd.to_datetime(df['date']).dt.day_name()
df

,date,DrCr,transaction_amount,balance,mode,name,Day,Month,Year,transaction_type,day_of_week
0,2022-01-01,Db,10000.0,473292.87,ATM,Unknown,1,1,2022,Debit,Saturday
1,2022-01-01,Db,10000.0,463292.87,ATM,Unknown,1,1,2022,Debit,Saturday
2,2022-01-02,Db,930.0,462362.87,UPI,AYUBRAJE,2,1,2022,Debit,Sunday
3,2022-01-07,Db,2000.0,460362.87,UPI,ABUTALAH,7,1,2022,Debit,Friday
4,2022-01-10,Db,1000.0,459362.87,UPI,AGRAWALB,10,1,2022,Debit,Monday
...,...,...,...,...,...,...,...,...,...,...,...
504,2023-10-06,Cr,41050.0,97647.67,CHEQUE,Unknown,6,10,2023,Credit,Friday
505,2023-10-06,Cr,107.8,97755.47,ECS,Unknown,6,10,2023,Credit,Friday
506,2023-10-06,Cr,23586.0,121341.47,UPI,DADAKHALA,6,10,2023,Credit,Friday
507,2023-10-06,Db,26286.0,95055.47,UPI,HDFCBANK,6,10,2023,Debit,Friday
508,2023-10-07,Db,100.0,94955.47,UPI,LAGADEKSA,7,10,2023,Debit,Saturday

**Task 13: Applying a Function to a Column**

In [32]:
# Apply a function to double the 'amount' column
df['double_amount'] = df['transaction_amount'].apply(lambda x: x * 2)
df

,date,DrCr,transaction_amount,balance,mode,name,Day,Month,Year,transaction_type,day_of_week,double_amount
0,2022-01-01,Db,10000.0,473292.87,ATM,Unknown,1,1,2022,Debit,Saturday,20000.0
1,2022-01-01,Db,10000.0,463292.87,ATM,Unknown,1,1,2022,Debit,Saturday,20000.0
2,2022-01-02,Db,930.0,462362.87,UPI,AYUBRAJE,2,1,2022,Debit,Sunday,1860.0
3,2022-01-07,Db,2000.0,460362.87,UPI,ABUTALAH,7,1,2022,Debit,Friday,4000.0
4,2022-01-10,Db,1000.0,459362.87,UPI,AGRAWALB,10,1,2022,Debit,Monday,2000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
504,2023-10-06,Cr,41050.0,97647.67,CHEQUE,Unknown,6,10,2023,Credit,Friday,82100.0
505,2023-10-06,Cr,107.8,97755.47,ECS,Unknown,6,10,2023,Credit,Friday,215.6
506,2023-10-06,Cr,23586.0,121341.47,UPI,DADAKHALA,6,10,2023,Credit,Friday,47172.0
507,2023-10-06,Db,26286.0,95055.47,UPI,HDFCBANK,6,10,2023,Debit,Friday,52572.0
508,2023-10-07,Db,100.0,94955.47,UPI,LAGADEKSA,7,10,2023,Debit,Saturday,200.0

**Task 14: Counting Unique Values**

In [33]:
# Count the number of unique transaction modes
unique_modes = df['mode'].nunique()
unique_modes

13

**Task 15: Checking for Duplicates**

In [34]:
# Find and display duplicate rows
duplicates = df[df.duplicated()]
duplicates

,date,DrCr,transaction_amount,balance,mode,name,Day,Month,Year,transaction_type,day_of_week,double_amount
307,2023-02-16,Db,5000.0,30744.13,ATM,Unknown,16,2,2023,Debit,Thursday,10000.0